files:
  - source: /docs/**/*
    ignore:
      - /changelogs/*.*
    translation: /i18n/%locale%/docusaurus-plugin-content-docs/current/**/%original_file_name%
  - source: /src/pages/**/*
    ignore:
      - /**/*.js
      - /**/*.jsx
      - /**/*.ts
      - /**/*.tsx
      - /**/*.css
    translation: i18n/%locale%/docusaurus-plugin-content-pages/**/%original_file_name%
  - source: /versioned_docs/**/*
    translation: /i18n/%locale%/docusaurus-plugin-content-docs/**/%original_file_name%
